[package]
name = "rust-dataframe"
version = "0.0.1"
authors = ["Neville Dipale <nevilledips@gmail.com>"]
edition = "2018"

[dependencies]
arrow = { git = "https://github.com/apache/arrow"}
# arrow = { path = "../../arrow/rust/arrow"}
num = "0.2"
num-traits = "0.2"
csv = "1"
byteorder = "1"
flatbuffers = "0.5"
array_tool = "1"
# TODO: using this to return schema with preserved order
serde_json = {version = "1", features = ["preserve_order"]}